
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - mern-network

  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mern-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
